services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600 # Check for updates every hour
      - WATCHTOWER_CLEANUP=true # Remove old images after updating
      - WATCHTOWER_REVIVE_STOPPED=true # Restart stopped containers after updating
