services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "${HOST_PORT}:5432"
    restart: unless-stopped 
    networks:
      - backend
      - storage

volumes:
  data:
    driver: local 

networks: 
  backend:
    external: true
    name: backend  
  storage:
    external: true
    name: storage


