services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:${APP_VERSION}
      container_name: "${APP_NAME}"
      restart: always
      ports:
       - '$APP_HTTP_PORT:8978'
      volumes: 
       - cloudbeaver:/opt/cloudbeaver/workspace             
      networks:
        - backend
        - storage


volumes:
  cloudbeaver:  

networks:
  backend:
    name: backend
    external: true 
  storage:
    name: storage 
    external: true
