services:
  mariadb:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${HOST_PORT}:3306"
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
