services:   

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${MEDIA_DIRECTORY}/movies:/data/movies
      - ${MEDIA_DIRECTORY}/tv:/data/tvshows
      - ${INSTALL_DIRECTORY}/jellyfin:/config
    ports:
      - 8096:8096
    restart: unless-stopped 
    networks:
      - media

  ############################################ 
  # 
  ############################################ 
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # other containers ports
      - "8080:8080"       # qbittorrent
    volumes:
      - ${INSTALL_DIRECTORY}/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
    restart: unless-stopped
    networks:
      - media
      - backend

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/sabnzbd:/config
      - ${USENET_INSTALL_DIR}/usenet:/data/usenet:rw 
    ports:
      - "8090:8080" # port mapping 
    restart: unless-stopped 
    networks:
      - media 
      - backend

  # qBitorrent is used to download torrents
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
    volumes:
      - ${DOWNLOAD_INSTALL_DIR}:/downloads
      - ${INSTALL_DIRECTORY}/qbittorrent:/config
    restart: unless-stopped
    network_mode: "service:gluetun"

  ############################################ 
  # 
  ############################################ 
  rdtclient:
    container_name: rdtclient
    volumes:
      - '${TORRENT_INSTALL_DIR}/torrents:/data/torrents'
      - '${INSTALL_DIRECTORY}/rdt:/data/db'
    image: rogerfar/rdtclient
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '6500:6500'
    networks:
      - media 
      - backend 

  ############################################ 
  # 
  ############################################ 
  bazarr:
    container_name: bazarr 
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/bazarr:/config
      - ${MEDIA_DIRECTORY}:/data/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media 
      - backend 

  ############################################ 
  # 
  ############################################ 
  lidarr:
    container_name: lidarr 
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - "8686:8686"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/lidarr:/config
      - ${MEDIA_DIRECTORY}:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media 
      - backend 

  ############################################ 
  # 
  ############################################ 
  prowlarr:
    container_name: prowlarr 
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"
    volumes:
      - ${INSTALL_DIRECTORY}/prowlarr:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media 
      - backend 

  ############################################ 
  # 
  ############################################ 
  radarr:
    container_name: radarr 
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/radarr:/config
      - ${MEDIA_DIRECTORY}:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media 
      - backend  
      
  ############################################ 
  # 
  ############################################ 
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${MEDIA_DIRECTORY}/books:/books
      - ${DOWNLOAD_INSTALL_DIR}/downloads:/downloads
      - ${INSTALL_DIRECTORY}/readarr:/config
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - media
      - backend

  ############################################ 
  # 
  ############################################ 
  sonarr:
    container_name: sonarr 
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/sonarr:/config
      - ${MEDIA_DIRECTORY}:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - media 
      - backend   

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Los_Angeles
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - media 
      - backend   

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID} # Replace with your user ID
      - PGID=${PGID} # Replace with your group ID
      - TZ=America/Los_Angeles # Replace with your timezone
    volumes:
      - ${INSTALL_DIRECTORY}/overseerr:/config
    ports:
      - 5056:5055
    restart: unless-stopped 
    networks: 
      - media 
      - backend 

  jellyseerr: 
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    environment: 
      - TZ=America/Los_Angeles
    ports: 
      - 5055:5055 
    volumes: 
      - ${INSTALL_DIRECTORY}/jellyseerr:/app/config 
    restart: unless-stopped  
    networks: 
      - media 
      - backend

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID} # Replace with your user ID
      - PGID=${PGID} # Replace with your group ID
      - TZ=America/Los_Angeles # Replace with your timezone
    volumes:
      - ${INSTALL_DIRECTORY}/calibre:/config/books # Replace with your Calibre library path
      - ${DOWNLOAD_INSTALL_DIR}:/downloads # Optional: for downloading books
    ports:
      - 8010:8080 
    networks: 
      - media 
      - backend

networks:
  backend:
    external: true
    name: backend
  media:
    external: true
    name: media 

