services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${MEDIA_DIRECTORY}/media/movies:/data/movies
      - ${MEDIA_DIRECTORY}/media/tv:/data/tvshows
      - ${INSTALL_DIRECTORY}/jellyfin:/config
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - media

  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - "8080:8080"
    volumes:
      - ${INSTALL_DIRECTORY}/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - media

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/sabnzbd:/config
      - ${USENET_INSTALL_DIR}:/data/usenet:rw
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    ports:
      - "8090:8080"
    restart: unless-stopped
    networks:
      - media
      - backend

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=911
      - PGID=911
      - WEBUI_PORT=8080
    volumes:
      - ${DOWNLOAD_INSTALL_DIR}:/downloads
      - ${TORRENT_INSTALL_DIR}:/data/torrents
      - ${INSTALL_DIRECTORY}/qbittorrent:/config
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    network_mode: "service:gluetun"

  rdtclient:
    container_name: rdtclient
    volumes:
      - '${TORRENT_INSTALL_DIR}:/data/torrents'
      - '${INSTALL_DIRECTORY}/rdt:/data/db'
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    image: rogerfar/rdtclient
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '6500:6500'
    networks:
      - media
      - backend

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/bazarr:/config
      - ${MEDIA_DIRECTORY}:/data/media
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - media
      - backend

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    ports:
      - "8686:8686"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/lidarr:/config
      - ${MEDIA_DIRECTORY}:/data
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - media
      - backend

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"
    volumes:
      - ${INSTALL_DIRECTORY}/prowlarr:/config
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - media
      - backend

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/radarr:/config
      - ${MEDIA_DIRECTORY}:/data
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - media
      - backend

  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${MEDIA_DIRECTORY}:/data
      - ${DOWNLOAD_INSTALL_DIR}:/downloads
      - ${INSTALL_DIRECTORY}/readarr:/config
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - media
      - backend

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/sonarr:/config
      - ${MEDIA_DIRECTORY}:/data
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - media
      - backend

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=UTC
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=true
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - backend
      - media

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${INSTALL_DIRECTORY}/overseerr:/config
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    ports:
      - 5056:5055
    restart: unless-stopped
    networks:
      - media
      - backend

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - TZ=America/Los_Angeles
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 5055:5055
    volumes:
      - ${INSTALL_DIRECTORY}/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media
      - backend

  reiverr:
    image: ghcr.io/aleksilassila/reiverr:latest
    container_name: reiverr
    ports:
      - 9494:9494
    environment:
      - SECRET=${SECRET}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${INSTALL_DIRECTORY}/reiverr:/config
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${MEDIA_DIRECTORY}/media/books:/config/books
      - ${MEDIA_DIRECTORY}/media/calibre-books:/config/calibre-books
      - ${DOWNLOAD_INSTALL_DIR}:/downloads
      - ./permissions.sh:/custom-cont-init.d/permissions.sh
    ports:
      - 8010:8080
      - 8011:8081
    networks:
      - media
      - backend

networks:
  backend:
    external: true
    name: backend
  media:
    external: true
    name: media
