services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8060:8080 # Dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # ro = read-only access to the docker.sock
      - /opt/appdata/traefik/:/etc/traefik/ 
      - ./logs/:/logs/
    networks:
      - proxy # rename this to your custom docker network 
      - frontend
      - backend 
    command:
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
    labels:
      traefik.http.routers.api.rule: Host(`traefik.jcdev.io`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    restart: unless-stopped

networks:  
  proxy: 
    external: true
    name: proxy
  frontend: 
    external: true
    name: frontend
  backend:
    external: true
    name: backend
