name: wireguard 
services:
    wireguard:
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
            - SERVERURL=vpn.overindex.co
            - SERVERPORT=51820
            - PEERS=2
            - PEERDNS=auto
            - INTERNAL_SUBNET=192.168.2.0
            - ALLOWEDIPS=192.168.1.0\24
            - LOG_CONFS=true
        volumes:
            - /etc/wireguard:/config
            - /lib/modules:/lib/modules
        restart: unless-stopped
        image: linuxserver/wireguard
