#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    ports:
      - '7575:7575'
    networks: 
      - proxy
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.entryPoints: https 

networks:
  proxy:
    external: true 
    name: proxy 
  frontend:
    external: true
    name: frontend
