version: "2.1" 
services:
  app: 
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy 
    volumes: 
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports: 
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped
